apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox01
    command: ["/bin/sh", "-c"]
    args: ["date >> /cache/date.txt; sleep 1000"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  - image: busybox
    name: busybox02
    command: ["/bin/sh", "-c"]
    args: ["cat /cache/date.txt; sleep 1000"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir: {}