apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - image: busybox
    name: container-1
    command: ["/bin/sh", "-c"]
    args: ["date >> /cache/date.txt; sleep 1000"]
    volumeMounts:
    - name: hostpath-volume
      mountPath: /cache
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp
      type: DirectoryOrCreate