apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
  nodeSelector: # this is a hard requirement - only schedule the pod if conditions are met
    disk: ssd