apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress-rules
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: connected-city.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: connectedcity-service
                port:
                  number: 80
    - host: connected-factory.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: connectedfactory-service
                port:
                  number: 80
