apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: r-monitoring
rules:
- apiGroups: ["*"] 
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: rb-monitoring
subjects:
- kind: ServiceAccount
  name: monitoring-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: r-monitoring
  apiGroup: ""

