apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: r-subresource
rules:
- apiGroups: [""]
  # Access logs and also exec into pod
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  # Access named resources
  resources: ["configmaps"]
  resourceNames: ["my-configmap"]
  verbs: ["update", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: rb-subresource
subjects:
- kind: User
  name: mike
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: r-subresource
  apiGroup: rbac.authorization.k8s.io

