apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service # match the service
subsets:
  - addresses:
      - ip: 54.67.74.115
    ports:
      - port: 80
        
