apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    # nodePort: 31000 ## should not give static nodeport.. leave it dynamic
  selector:
    run: nginx
  type: NodePort
