apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
spec:
  limits:
  - type: Container # valid per container
    max: # ~ limit
      cpu: "1"
      memory: "512Mi"
    min: # ~ request
      cpu: "100m"
      memory: "64Mi"
