apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-default-limit-range
spec:
  limits:
  - type: Container # valid per container
    default: # ~ limit
      cpu: "1"
      memory: "512Mi"
    defaultRequest: # ~ request
      cpu: "100m"
      memory: "64Mi"
