apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  restartPolicy: Never
  containers:
  - image: ubuntu
    name: c1
    command: ["/bin/sh"]
    # args: ["-c", "while true; do echo c1; sleep 5; done"]
    args: ["-c", "echo c1; sleep 5"]
  - image: ubuntu    
    name: c2
    command: ["/bin/sh"]
    # args: ["-c", "while true; do echo c2; sleep 5; done"]
    args: ["-c", "exit 1"]
