apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
  labels:
    app: sidecar
spec:
  containers:
  - name: application
    image: alpine
    command: ['/bin/sh', '-c', 'while true; do date > /var/log/index.html; sleep 2; done'] 
    volumeMounts:
    - name: scratch
      mountPath: "/var/log"
  - name: nginx
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: scratch
      mountPath: "/usr/share/nginx/html" 
  volumes:
  - name: scratch
    emptyDir: {}
--- 
apiVersion: v1
kind: Service
metadata:
  name: html
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sidecar