apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-demo-pod
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    - containerPort: 90
  restartPolicy: Always
