apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  annotations:
    scrape: "true"
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
  restartPolicy: Always
