apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - command: ["printenv"]
    args: ["HOSTNAME"]
    image: ubuntu
    name: ubuntu
  restartPolicy: Never
