apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data: # secrets are store in etcd in based64 format
  PASS: MTIzNA== 
  USER: cm9vdA==
stringData: # stringData will be encoded in base64 in etcd
  secret.conf: |
    USER: Big D
    PASS: onlyHas6Inches

# k get secret test --template={{.data.PASS}} | base64 -d 

# k get secret test -o jsonpath='{.data.PASS}' | base64 -d 

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    
    # command: ['/bin/echo']
    # args: ['$(USER)']
    # env:
    # - name: USER
    #   valueFrom:
    #     secretKeyRef:
    #       name: secret-demo
    #       key: USER

    # command: ['/bin/sh', '-c']
    # args: ['env']
    # envFrom: # inject all secrets at once
    # - secretRef:
    #     name: secret-demo

    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume

  volumes:
    - name: secret-volume
      secret:
        secretName: secret-demo
      
